name: Python Django Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#env:
#  # Setting an environment variable with the value of a configuration variable
#  DJANGO_SECRET_KEY: ${{ vars.DJANGO_SECRET_KEY }}
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: Test
        run: |
          python manage.py migrate
          pytest
